#!/bin/bash

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

docker push coderus/sailfishos-platform-sdk-base:latest
docker push coderus/sailfishos-platform-sdk-base:$RELEASE

docker push coderus/sailfishos-platform-sdk:latest
docker push coderus/sailfishos-platform-sdk:$RELEASE
