FROM coderus/sailfishos-platform-sdk-base-tooling
MAINTAINER Andrey Kozhevnikov <coderusinbox@gmail.com>

ARG RELEASE
ARG ARCH

COPY build/target-$ARCH.tar /target-$ARCH.tar

RUN <<EOF
set -ex
sudo ssu lr
sudo zypper ref
sdk-assistant -y create SailfishOS-$RELEASE-$ARCH /target-$ARCH.tar
sudo rm -f /target-$ARCH.tar
sudo rm -rf /var/cache/zypp/*
sudo rm -rf /srv/mer/targets/SailfishOS-$RELEASE-$ARCH/var/cache/zypp/*
EOF
