FROM coderus/sailfishos-platform-sdk-base
MAINTAINER Andrey Kozhevnikov <coderusinbox@gmail.com>

ARG RELEASE

COPY build/tooling-i486.tar /tooling-i486.tar

USER nemo
WORKDIR /

RUN set -ex ;\
 sudo mkdir /host_targets ;\
 sudo zypper ref ;\
 sdk-assistant -y create SailfishOS-$RELEASE /tooling-i486.tar ;\
 sudo rm -f /tooling-i486.tar ;\
 sudo rm -rf /var/cache/zypp/*